#
#
## Nacos ??
##spring.cloud.nacos.discovery.username=nacos
##spring.cloud.nacos.discovery.password=nacos
##spring.cloud.nacos.discovery.server-addr=localhost:8848
##spring.cloud.nacos.discovery.namespace=c73c948c-d8d7-4aa9-a10a-10e4cfcb5eeb
##
##spring.cloud.nacos.config.server-addr=${spring.cloud.nacos.discovery.server-addr}
##spring.cloud.nacos.config.username=nacos
##spring.cloud.nacos.config.password=nacos
##spring.cloud.nacos.config.contextPath=/nacos
##spring.cloud.nacos.config.namespace=${spring.cloud.nacos.discovery.namespace}
##
##spring.config.import=nacos:bill-server.properties?refresh=true
## ========== Dubbo ??????? ==========
#dubbo.application.name=${spring.application.name}
#dubbo.provider.timeout=5000
##dubbo.provider.tag=gray
##dubbo.register-mode: instance
#dubbo.application.register-mode=instance
#dubbo.metadata.report.address=nacos://localhost:8848?namespace=c73c948c-d8d7-4aa9-a10a-10e4cfcb5eeb
#dubbo.registry.address=nacos://localhost:8848?namespace=c73c948c-d8d7-4aa9-a10a-10e4cfcb5eeb&username=nacos&password=nacos
#
##rocketmq.consumer.namespace=localhost:9876
#rocketmq.name-server=localhost:9876
#rocketmq.consumer-config.order.group=order-pull-group
#rocketmq.consumer-config.order.topic=order-topic
#rocketmq.consumer-config.log.group=log-pull-group
#rocketmq.consumer-config.log.topic=log-topic
##rocketmq.consumer.group=myProducerGroup
